# bStats collects some data for plugin authors like how many servers are using their plugins.
# To honor their work, you should not disable it.
# This has nearly no effect on the server performance!
# Check out https://bStats.org/ to learn more :)
enabled: true
serverUuid: 859c1bf1-8cdc-457a-b49e-cd7f2b5ae146
logFailedRequests: false
